name: Daily OWASP Scan

on:
  schedule:
    - cron: '0 8 * * *' # Runs the job every day at 8:00 AM UTC

jobs:
  owasp_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-java@v4.2.1
      with:
        cache: gradle
        distribution: 'zulu'
        java-version: '21'

    - name: Run OWASP Scan
      run: make owaspScan
